name: sample-workflow-01

on: push

jobs:
  sample-job-01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Multiline Execution
        run: |
              echo "First github actions step"
              ls -al
              cat README.md
      
      #- name: List Files
      #  run: 
      #
      #- name: Read Files
      #  run: 
      #
      #- name: Checkout Repo Path
      #  run: echo $GITHUB_WORKSPACE