name: generate-ascii

on: push

jobs:
  ascii-job-01:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -al
        
      - name: Execute Shell Script
        run: |
            chmod +x ascii-cowsay.sh
            ./ascii-cowsay.sh